[package]
name = "assignment_6"
version = "0.1.0"
authors = ["Shahzad Ahmad <shahzad.ahmad1@telenor.com.pk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="0.7.3"